functions = require("lib.functions")
local sounds = require("__base__.prototypes.entity.sounds")
local vanillaResistance = data.raw["cargo-wagon"]["cargo-wagon"].resistances

data:extend(
{
	{
		type = "fluid-wagon",
		name = "y_wagon_tank_fm1",
		icon = "__yi_railway__/graphics/icons/railway/4atw_fm1_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		minable = {mining_time = 0.5, result = "y_wagon_tank_fm1"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600,
		capacity = 25000,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		gui_front_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/front-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_center_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/center-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_back_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/back-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_connect_front_center_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/connector-front-center.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_connect_center_back_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/connector-center-back.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_front_center_tank_indiciation =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/1.png",
			width = 32,
			height = 32,
			flags = {"icon"}
		},
		gui_center_back_tank_indiciation =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/2.png",
			width = 32,
			height = 32,
			flags = {"icon"}
		},
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.5,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 4,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = crash_trigger(),
	},

	{
		type = "fluid-wagon",
		name = "y_wagon_tank_fm2",
		icon = "__yi_railway__/graphics/icons/railway/4atw_fm2_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 0,
		minable = {mining_time = 0.5, result = "y_wagon_tank_fm2"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600,
		capacity =  25000,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		gui_front_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/front-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_center_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/center-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_back_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/back-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_connect_front_center_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/connector-front-center.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_connect_center_back_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/connector-center-back.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_front_center_tank_indiciation =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/1.png",
			width = 32,
			height = 32,
			flags = {"icon"}
		},
		gui_center_back_tank_indiciation =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/2.png",
			width = 32,
			height = 32,
			flags = {"icon"}
		},
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.5,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 4,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = crash_trigger(),
	},

	{
		type = "fluid-wagon",
		name = "yir_wagon_tank_orange",
		icon = "__yi_railway__/graphics/icons/railway/4a-fw-acid_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		minable = {mining_time = 0.5, result = "yir_wagon_tank_orange"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600,
		capacity = 50000,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		gui_front_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/front-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_center_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/center-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_back_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/back-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_connect_front_center_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/connector-front-center.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_connect_center_back_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/connector-center-back.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_front_center_tank_indiciation =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/1.png",
			width = 32,
			height = 32,
			flags = {"icon"}
		},
		gui_center_back_tank_indiciation =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/2.png",
			width = 32,
			height = 32,
			flags = {"icon"}
		},

		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.4,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 4,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = crash_trigger(),
	},

	{
		type = "fluid-wagon",
		name = "yir_wagon_tank_blue",
		icon = "__yi_railway__/graphics/icons/railway/4a-fw-blue_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		capacity = 50000,
		minable = {mining_time = 0.5, result = "yir_wagon_tank_blue"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		gui_front_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/front-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_center_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/center-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_back_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/back-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_connect_front_center_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/connector-front-center.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_connect_center_back_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/connector-center-back.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_front_center_tank_indiciation =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/1.png",
			width = 32,
			height = 32,
			flags = {"icon"}
		},
		gui_center_back_tank_indiciation =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/2.png",
			width = 32,
			height = 32,
			flags = {"icon"}
		},

		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.5,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 4,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = crash_trigger(),
	},

	{
		type = "fluid-wagon",
		name = "yir_fw4a_tank_oil",
		icon = "__yi_railway__/graphics/icons/railway/4afw_oil_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		minable = {mining_time = 0.5, result = "yir_fw4a_tank_oil"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 1000,
		capacity = 37500,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		gui_front_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/front-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_center_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/center-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_back_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/back-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_connect_front_center_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/connector-front-center.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_connect_center_back_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/connector-center-back.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_front_center_tank_indiciation =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/1.png",
			width = 32,
			height = 32,
			flags = {"icon"}
		},
		gui_center_back_tank_indiciation =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/2.png",
			width = 32,
			height = 32,
			flags = {"icon"}
		},
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.55,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 4,
		energy_per_hit_point = 8,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = crash_trigger(),
	},

	{
		type = "fluid-wagon",
		name = "yir_fw4_vc",
		icon = "__yi_railway__/graphics/icons/railway/4aw_fw_vc_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		minable = {mining_time = 0.5, result = "yir_fw4_vc"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 1000,
		capacity = 50000,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		gui_front_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/front-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_center_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/center-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_back_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/back-tank.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_connect_front_center_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/connector-front-center.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_connect_center_back_tank =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/connector-center-back.png",
			width = 64,
			height = 64,
			flags = {"icon"}
		},
		gui_front_center_tank_indiciation =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/1.png",
			width = 32,
			height = 32,
			flags = {"icon"}
		},
		gui_center_back_tank_indiciation =
		{
			filename = "__base__/graphics/entity/fluid-wagon/gui/2.png",
			width = 32,
			height = 32,
			flags = {"icon"}
		},
		weight = 1000,
		max_speed = 2.0,
		braking_force = 2,
		friction_force = 0.4,
		air_resistance = 0.01,
		connection_distance = 3,
		joint_distance = 4,
		energy_per_hit_point = 8,
		resistances =
		{
			{type = "fire", decrease = 0, percent = 90},
			{type = "physical", decrease = 0, percent = 90},
			{type = "impact", decrease = 0, percent = 90},
			{type = "explosion", decrease = 0, percent = 90},
			{type = "acid", decrease = 0, percent = 90},
			{type = "laser", decrease = 0, percent = 70},
			{type = "electric", decrease = 0, percent = 70},
		},
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = crash_trigger(),
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_purple",
		icon = "__yi_railway__/graphics/icons/railway/4a-kw-s1-icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 10,
		minable = {mining_time = 0.5, result = "yir_4acw_purple"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 1000,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 2,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances =
		{
			{type = "fire", decrease = 0, percent = 90},
			{type = "physical", decrease = 0, percent = 90},
			{type = "impact", decrease = 0, percent = 90},
			{type = "explosion", decrease = 0, percent = 90},
			{type = "acid", decrease = 0, percent = 90},
			{type = "laser", decrease = 0, percent = 70},
			{type = "electric", decrease = 0, percent = 70},
		},

		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = crash_trigger(),
		open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.75},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_oceanblue",
		icon = "__yi_railway__/graphics/icons/railway/4a-bw-s2-icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "yir_4acw_oceanblue"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 500,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = crash_trigger(),
		open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.75},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_grey",
		icon = "__yi_railway__/graphics/icons/railway/4a-tw-s3-icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "yir_4acw_grey"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 500,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = crash_trigger(),
		open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.75},
	},
	
	{
		type = "cargo-wagon",
		name = "yir_4acw_coal",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cw_coal_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "yir_4acw_coal"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
		crash_trigger = crash_trigger(),
		open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.75},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_iron",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cw_iron_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "yir_4acw_iron"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
		crash_trigger = crash_trigger(),
		open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.75},
	},
	
	{
		type = "cargo-wagon",
		name = "yir_4acw_copper",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cw_copper_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "yir_4acw_copper"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
		crash_trigger = crash_trigger(),
		open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.75},
	},
	
	{
		type = "cargo-wagon",
		name = "yir_4acw_stone",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cw_stone_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "yir_4acw_stone"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
		crash_trigger = crash_trigger(),
		open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.75},
	},
	
	{
		type = "cargo-wagon",
		name = "yir_4acw_wood",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_wood_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "yir_4acw_wood"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
		crash_trigger = crash_trigger(),
		open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.75},
	},
	
	{
		type = "cargo-wagon",
		name = "yir_4acw_closed",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_closed_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "yir_4acw_closed"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
		crash_trigger = crash_trigger(),
		open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.75},
	},
	
	{
		type = "cargo-wagon",
		name = "yir_4acw_gold",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_gold_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "yir_4acw_gold"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
		crash_trigger = crash_trigger(),
		open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.75},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_mun",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_mun_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "yir_4acw_mun"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
		crash_trigger = crash_trigger(),
		open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.75},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_tf",
		icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_tf_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "yir_4acw_tf"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.5,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
		crash_trigger = crash_trigger(),
		open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.75},
	},

	{
		type = "cargo-wagon",
		name = "yir_4acw_vc",
		icon = "__yi_railway__/graphics/icons/railway/4a-cw_vc_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "yir_4acw_vc"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 1000, corpse = "medium-remnants", dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1, -2.7}, {1, 3.3}},
		vertical_selection_shift = -0.5,
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 2.0,
		braking_force = 2,
		friction_force = 0.4,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances =
		{
			{type = "fire", decrease = 0, percent = 90},
			{type = "physical", decrease = 0, percent = 90},
			{type = "impact", decrease = 0, percent = 90},
			{type = "explosion", decrease = 0, percent = 90},
			{type = "acid", decrease = 0, percent = 90},
			{type = "laser", decrease = 0, percent = 70},
			{type = "electric", decrease = 0, percent = 70},
		},
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
		tie_distance = 50,
		working_sound =	{sound = {filename = "__base__/sound/train-wheels.ogg", volume = 0.5}, match_volume_to_activity = true},
		crash_trigger = crash_trigger(),
		open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.75},
	},
})