data:extend({
{
   type = "item",
   name = "yir_diesel_monument",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/yir_diesel_monument_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_workshop",
   order = "D",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_diesel_monument",
},
{
   type = "item",
   name = "yir_fuel_fluid_u3",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/fuel_gas.png",
   group = "yuoki_railway",
   subgroup = "yir_support",
   order = "f4",
   stack_size = 2500,
   default_request_amount = 100,
   fuel_value = "2MJ",
   fuel_category = "yr_diesel",
},
{
   type = "item",
   name = "yir_fuel_fluid_u2",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/fuel_light.png",
   group = "yuoki_railway",
   subgroup = "yir_support",
   order = "f5",
   stack_size = 2500,
   default_request_amount = 100,
   fuel_value = "4MJ",
   fuel_category = "yr_diesel",
},
{
   type = "item",
   name = "yir_fuel_fluid_u1",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/fuel_diesel.png",
   group = "yuoki_railway",
   subgroup = "yir_support",
   order = "f6",
   stack_size = 2500,
   default_request_amount = 100,
   fuel_value = "3MJ",
   fuel_category = "yr_diesel",
},
{
   type = "item",
   name = "yir_fuel_energy_u1",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/fuel_energy.png",
   group = "yuoki_railway",
   subgroup = "yir_support",
   order = "f6",
   stack_size = 2500,
   default_request_amount = 100,
   fuel_value = "10MJ",
   fuel_category = "yr_future",
},
{
   type = "item",
   name = "yir_lamp_clock",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/yir_clock_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_support",
   order = "l3",
   stack_size = 100,
   default_request_amount = 10,
   place_result = "yir_lamp_clock",
},
{
   type = "item",
   name = "yir_lamp_old1",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/yir_lamp_old1_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_support",
   order = "l2",
   stack_size = 100,
   default_request_amount = 10,
   place_result = "yir_lamp_old1",
},
{
   type = "item",
   name = "yir_lamp_modern",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/yir_lamp_modern_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_support",
   order = "l1",
   stack_size = 100,
   default_request_amount = 10,
   place_result = "yir_lamp_modern",
},
{
   type = "item",
   name = "yir_future_coin",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/future_coin_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_parts",
   order = "x3",
   stack_size = 1000,
   default_request_amount = 50,
},
{
   type = "item",
   name = "yir_diesel_coin",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/diesel_coin_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_parts",
   order = "x2",
   stack_size = 1000,
   default_request_amount = 50,
},
{
   type = "item",
   name = "yir_loco_del_KR",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/kurts_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_diesel",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_loco_del_KR",
},
{
   type = "item",
   name = "yir_4acw_tf",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_tf_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_4acw_tf",
},
{
   type = "item",
   name = "yir_4acw_mun",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_mun_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_4acw_mun",
},
{
   type = "item",
   name = "yir_4acw_gold",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_gold_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_4acw_gold",
},
{
   type = "item",
   name = "yir_4acw_closed",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_closed_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_4acw_closed",
},
{
   type = "item",
   name = "yir_4acw_wood",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/4aw_cargo_wood_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_4acw_wood",
},
{
   type = "item",
   name = "yir_4acw_stone",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/4aw_cw_stone_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_4acw_stone",
},
{
   type = "item",
   name = "yir_4acw_copper",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/4aw_cw_copper_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_4acw_copper",
},
{
   type = "item",
   name = "yir_4acw_iron",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/4aw_cw_iron_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_4acw_iron",
},
{
   type = "item",
   name = "yir_4acw_coal",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/4aw_cw_coal_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_4acw_coal",
},
{
   type = "item",
   name = "yir_fuel_energy",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/fuel_cell_e.png",
   group = "yuoki_railway",
   subgroup = "yir_support",
   order = "f3",
   stack_size = 30,
   default_request_amount = 20,
   fuel_value = "40MJ",
   fuel_category = "chemical",
},
{
   type = "item",
   name = "yir_fuel_diesel",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/diesel.png",
   group = "yuoki_railway",
   subgroup = "yir_support",
   order = "f2",
   stack_size = 50,
   default_request_amount = 20,
   fuel_value = "50MJ",
   fuel_category = "yr_diesel",
},
{
   type = "item",
   name = "yir_fuel_coks",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/coks.png",
   group = "yuoki_railway",
   subgroup = "yir_support",
   order = "f1",
   stack_size = 30,
   default_request_amount = 20,
   fuel_value = "35MJ",
   fuel_category = "chemical",
},
{
   type = "item",
   name = "yir_frame_loco_future",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/frame_future.png",
   group = "yuoki_railway",
   subgroup = "yir_material",
   order = "a",
   stack_size = 100,
   default_request_amount = 5,
},
{
   type = "item",
   name = "yir_frame_loco_diesel",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/frame_diesel.png",
   group = "yuoki_railway",
   subgroup = "yir_material",
   order = "a",
   stack_size = 100,
   default_request_amount = 5,
},
{
   type = "item",
   name = "yir_frame_loco_steam",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/frame_steam.png",
   group = "yuoki_railway",
   subgroup = "yir_material",
   order = "a",
   stack_size = 100,
   default_request_amount = 5,
},
{
   type = "item",
   name = "yir_frame_waggon",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/frame_wagon.png",
   group = "yuoki_railway",
   subgroup = "yir_material",
   order = "a",
   stack_size = 100,
   default_request_amount = 5,
},
{
   type = "item",
   name = "yir_radsatz_locos",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/radsatz_locomotive.png",
   group = "yuoki_railway",
   subgroup = "yir_material",
   order = "a",
   stack_size = 100,
   default_request_amount = 5,
},
{
   type = "item",
   name = "yir_radsatz_waggon",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/radsatz_waggon.png",
   group = "yuoki_railway",
   subgroup = "yir_material",
   order = "a",
   stack_size = 100,
   default_request_amount = 5,
},
{
   type = "item",
   name = "yir_color_white",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/paint_white.png",
   group = "yuoki_railway",
   subgroup = "yir_material",
   order = "a",
   stack_size = 100,
   default_request_amount = 5,
},
{
   type = "item",
   name = "yir_color_green",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/paint_green.png",
   group = "yuoki_railway",
   subgroup = "yir_material",
   order = "a",
   stack_size = 100,
   default_request_amount = 5,
},
{
   type = "item",
   name = "yir_color_black",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/paint_black.png",
   group = "yuoki_railway",
   subgroup = "yir_material",
   order = "a",
   stack_size = 100,
   default_request_amount = 5,
},
{
   type = "item",
   name = "yir_color_blue",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/paint_blue.png",
   group = "yuoki_railway",
   subgroup = "yir_material",
   order = "a",
   stack_size = 100,
   default_request_amount = 5,
},
{
   type = "item",
   name = "yir_color_red",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/paint_red.png",
   group = "yuoki_railway",
   subgroup = "yir_material",
   order = "a",
   stack_size = 100,
   default_request_amount = 5,
},
{
   type = "item",
   name = "yir_loco_fesw_op",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/DESW90-OP-icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_diesel",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_loco_fesw_op",
},
{
   type = "item",
   name = "yir_2acw_wood",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/cws_wood-icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_2acw_wood",
},
{
   type = "item",
   name = "yir_2acw_3blocks",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/2a_cws_tf1-icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_2acw_3blocks",
},
{
   type = "item",
   name = "yir_coin",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/yir-coin-icon.png",
   group = "yuoki_railway",
   subgroup = "yir_parts",
   order = "x1",
   stack_size = 1000,
   default_request_amount = 150,
},
{
   type = "item",
   name = "yir_factory_loco",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/factories/yir_fac_loco_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_workshop",
   order = "A1",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_factory_loco",
},
{
   type = "item",
   name = "yir_factory_wagon",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/factories/yir_fac_waggon_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_workshop",
   order = "B",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_factory_wagon",
},
{
   type = "item",
   name = "yir_factory_tiles",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/factories/yir_fac_tiles_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_workshop",
   order = "E",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_factory_tiles",
},
{
   type = "item",
   name = "yir_factory_material",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/factories/yir_fac_parts_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_workshop",
   order = "C",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_factory_material",
},
{
   type = "item",
   name = "yir_factory_stuff",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/factories/yir_fab_coins_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_workshop",
   order = "D",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_factory_stuff",
},
{
   type = "item",
   name = "y_tgb",
   icon_size = 32,
   icon = "__yi_railway__/graphics/path_tiles/floor_tplate.png",
   group = "yuoki_railway",
   subgroup = "yir_floor",
   order = "a",
   stack_size = 500,
   default_request_amount = 5,
},
{
   type = "item",
   name = "y_tring",
   icon_size = 32,
   icon = "__yi_railway__/graphics/path_tiles/stripes.png",
   group = "yuoki_railway",
   subgroup = "yir_floor",
   order = "a",
   stack_size = 500,
   default_request_amount = 5,
},
{
   type = "item",
   name = "y_path_checker",
   icon_size = 32,
   icon = "__yi_railway__/graphics/path_tiles/labor_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_floor",
   order = "a",
   stack_size = 500,
   default_request_amount = 5,
},
{
   type = "item",
   name = "y_loco_emd1500black_v2",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/DESW90-BL-icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_diesel",
   order = "b4",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_loco_emd1500black_v2",
},
{
   type = "item",
   name = "y_loco_emd1500blue_v2",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/emd-1500_blue2_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_diesel",
   order = "b3",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_loco_emd1500blue_v2",
},
{
   type = "item",
   name = "yir_loco_del_mk1400",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/emd-gp_orange_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_diesel",
   order = "d3",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_loco_del_mk1400",
},
{
   type = "item",
   name = "yir_loco_del_bluegray",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/emd-gp_bluegray_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_diesel",
   order = "d2",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_loco_del_bluegray",
},
{
   type = "item",
   name = "yir_loco_sel_blue",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/rsea_blue_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_steam",
   order = "c2",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_loco_sel_blue",
},
{
   type = "item",
   name = "yir_4acw_grey",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/4a-tw-s3-icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons_4A",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_4acw_grey",
},
{
   type = "item",
   name = "yir_4acw_oceanblue",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/4a-bw-s2-icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons_4A",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_4acw_oceanblue",
},
{
   type = "item",
   name = "yir_4acw_purple",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/4a-kw-s1-icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons_4A",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "yir_4acw_purple",
},
{
   type = "item",
   name = "y_wagon_tank_fm2",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/4atw_fm2_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_fluidwagons_4A",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_tank_fm2",
},
{
   type = "item",
   name = "y_wagon_tank_fm1",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/4atw_fm1_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_fluidwagons_4A",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_tank_fm1",
},
{
   type = "item",
   name = "y_wagon_tender_green",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/rtender_green_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_tender_green",
},
{
   type = "item",
   name = "y_wagon_tender_black",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/rtender_black_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_tender_black",
},
{
   type = "item",
   name = "y_loco_fs_steam_green",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/rsea_green_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_steam",
   order = "c1",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_loco_fs_steam_green",
},
{
   type = "item",
   name = "y_loco_emd3000_white",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/emd_gp_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_diesel",
   order = "d1",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_loco_emd3000_white",
},
{
   type = "item",
   name = "y_wagon_corn_blue",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/2a_corn_blue_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_corn_blue",
},
{
   type = "item",
   name = "y_wagon_corn_green",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/2a_corn_green_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_corn_green",
},
{
   type = "item",
   name = "y_wagon_hopper_yellow",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/2a_hooper_y_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_hopper_yellow",
},
{
   type = "item",
   name = "y_wagon_zement_white",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/cws64_zement_white_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_zement_white",
},
{
   type = "item",
   name = "y_wagon_zement_gray",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/cws64_zement_gray_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_zement_gray",
},
{
   type = "item",
   name = "y_loco_emd1500black",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/emd-1500_black_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_diesel",
   order = "b2",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_loco_emd1500black",
},
{
   type = "item",
   name = "y_loco_emd1500blue",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/emd-1500_blue_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_diesel",
   order = "b1",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_loco_emd1500blue",
},
{
   type = "item",
   name = "y_wagon_closed",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/wcs_closed_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_closed",
},
{
   type = "item",
   name = "y_wagon_tank_orange",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/wcs_tank_orange_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_fluidwagons_4A",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_tank_orange",
},
{
   type = "item",
   name = "y_wagon_tank_blue",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/wcs_tank_blue_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_fluidwagons_4A",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_tank_blue",
},
{
   type = "item",
   name = "y_wagon_copper",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/cws_rcopper_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_copper",
},
{
   type = "item",
   name = "y_wagon_iron",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/cws_riron_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_iron",
},
{
   type = "item",
   name = "y_wagon_stone",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/cws_rstone_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_stone",
},
{
   type = "item",
   name = "y_loco_desw_orange",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/des_orange_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_diesel",
   order = "a2",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_loco_desw_orange",
},
{
   type = "item",
   name = "y_loco_desw_blue",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/des_blue_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_diesel",
   order = "a3",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_loco_desw_blue",
},
{
   type = "item",
   name = "y_loco_ses_std",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/sea-ss-icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_diesel",
   order = "a1",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_loco_ses_std",
},
{
   type = "item",
   name = "y_loco_ses_red",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/sea-sr-icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_diesel",
   order = "a2",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_loco_ses_red",
},
{
   type = "item",
   name = "y_wagon_trans",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/cws_trans_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_trans",
},
{
   type = "item",
   name = "y_wagon_coal",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/cws_rcoal_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_cargowagons",
   order = "a",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_wagon_coal",
},
{
   type = "item",
   name = "y_path_science",
   icon_size = 32,
   icon = "__yi_railway__/graphics/path_tiles/vent_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_floor",
   order = "p2",
   stack_size = 500,
   default_request_amount = 5,
},
{
   type = "item",
   name = "y_path_labor",
   icon_size = 32,
   icon = "__yi_railway__/graphics/path_tiles/floor004_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_floor",
   order = "p1",
   stack_size = 500,
   default_request_amount = 5,
},
{
   type = "item",
   name = "y_path_slag",
   icon_size = 32,
   icon = "__yi_railway__/graphics/path_tiles/pslag_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_floor",
   order = "p0",
   stack_size = 500,
   default_request_amount = 5,
},
{
   type = "item",
   name = "y_loco_desw",
   icon_size = 64,
   icon = "__yi_railway__/graphics/icons/railway/des_green_icon.png",
   group = "yuoki_railway",
   subgroup = "yir_locomotives_diesel",
   order = "a1",
   stack_size = 10,
   default_request_amount = 5,
   place_result = "y_loco_desw",
},

})